### ISSUE TITLE
[Jason: 03] Oversteer Technique 

### ISSUE THREAD

**Issue by rah1993** [infiniteflight/infiniteflight-docs#495]
**Location:**

https://staging.infiniteflight.com/guide/flying-guide/take-off-to-cruise/before-take-off

Placed just under the pro tip at the bottom of the page

**Action Required:**

- Low priority but would be nice to illustrate the oversteer technique in an image if you get some time
- I've realised in my drawing I've put runway "09L" but maybe "9L" is better to align with IF

![IMG_D9DB2D808561-1](https://user-images.githubusercontent.com/56978356/142201499-e4f68539-0a30-4941-b925-52a2afc136f8.jpeg)

![oversteering technique](https://user-images.githubusercontent.com/56978356/142201521-d5708d1e-fbc7-46fd-bbb7-78371f8ab3f5.jpg)

<img width="394" alt="Screenshot 2021-11-17 at 12 35 57" src="https://user-images.githubusercontent.com/56978356/142201749-9cc6aaab-71c8-49a0-ba6a-cc8913b90933.png">

**Comment by linkhousemedia** [comment]
Voila. Let me know if you want any tweaks. 

![oversteer](https://github.com/user-attachments/assets/70190346-f53e-4d95-9d2b-29c6b1eaf236)
