### ISSUE TITLE
Using Must

### ISSUE THREAD

**Issue by Gonzo1994** [infiniteflight/infiniteflight-docs#608]
While must can be used to be mandatory, in the world of requirements, SHALL is the only legal and universally viable word that should used. 

Would suggest replacing any must with shall to avoid any complication as what is required and what is suggestive or advisory.

**Comment by rah1993** [comment]
Thank you for the suggestion. Although I take the point, MUST and SHOULD are still very common phrases to find in manuals, and as well as being defined at the start of our manuals on their intended purpose, I think it would be difficult to confuse what the meaning of these phrases is.

I think it might be best to avoid making this change to prevent confusion as we have used these phrases for a very long time now, but I will review this in the new year in any case. Thank you
