### ISSUE TITLE
[Jason: 01] Change numbers on Intercepting LOC ATC image

### ISSUE THREAD

**Issue by rah1993** [infiniteflight/infiniteflight-docs#626]
**Location:**

https://infiniteflight.com/guide/atc-manual/6.-radar/6.10-instrument-landing-system-(ils)-approach#6.10.3

**Action Required:**

- [ ] change runway designator from 09 to 27
- [ ] change the three headings from 060/090/120 to 240/270/300 respectively

<img width="818" alt="Screenshot 2023-05-17 at 18 37 55" src="https://github.com/infiniteflight/infiniteflight-docs/assets/56978356/43e1fbd5-0b2b-49a6-8428-acdbcb29a5ca">

**Comment by linkhousemedia** [comment]
Looks like I did this already. Hopefully, it's updated and we forgot to close this!! If not, here it is. 

![atc-intercept-loc](https://github.com/user-attachments/assets/aad65357-671e-43a9-baab-790cd3b0ffdf)
