### ISSUE TITLE
[Jason: 02] Indent on bullet points

### ISSUE THREAD

**Issue by rah1993** [infiniteflight/infiniteflight-docs#632]
**Location:**

All guides ([example](https://staging.infiniteflight.com/guide/getting-started-guide/home-user-interface/flight#free-flight))

**Action Required:**

When there is more than two lines of text, the indent by the bullet point "resets". Ideally would like the indent to continue regardless of how many lines are present (try to keep the content to a minimum for bullet points but they are used in guides with numbers to highlight the UI so sometimes is unavoidable

See the example below at number 4:
 
<img width="873" alt="Screenshot 2023-06-02 at 11 47 34" src="https://github.com/infiniteflight/infiniteflight-docs/assets/56978356/eb99c21c-1c10-4845-99df-853dcd9d3b8d">

**Comment by linkhousemedia** [comment]
I've pushed a change for this and Cam will deploy to staging at his convenience.

**Comment by linkhousemedia** [comment]
Sample in staging:

https://staging.infiniteflight.com/guide/getting-started-guide/home-user-interface/home-screen
