### ISSUE TITLE
Graphics for Scenery Editing Team

### ISSUE THREAD

**Issue by rah1993** [infiniteflight/infiniteflight-docs#676]
- [x] recruitment banner to be used on new recruitment thread, maybe same format as IFATC one [here](https://community.infiniteflight.com/t/atc-recruiting/843545)?
- [x] new roundel symbol to be used on Discord channel
- [x] maybe also files of just the new logo itself with Infinite Flight Scenery Editing next to it so we have this if needed going forward (same theme as the IFATC one)

**Comment by linkhousemedia** [comment]
You should have access to this: [https://drive.google.com/drive/folders/1cRY4JKxaRlR9OVNCji7FqMtk_XhbklVl](https://drive.google.com/drive/folders/1cRY4JKxaRlR9OVNCji7FqMtk_XhbklVl)

I'm hesitant to do a general-use logo other than the one that's in the folder, but if you need something specific (like a horizontal version) I'm happy to do that.
