### ISSUE TITLE
Vuelo libre 

### ISSUE THREAD

**Issue by Meme20277811** [infiniteflight/infiniteflight-docs#678]
Hola yo solo quiero que aunque no tenga el infinite flight pro se puedan aser vuelos osea que te cuenten los vuelos y teden puntos por el vuelo porque le dan puntos de vuelo solo a los que tienen infinite flight pro yo solo quiero aser mis vuelos con personas y aviones comerciales, solo eso quisiera pero el juego de lo contrario está bien bueno y divertido

**Comment by carmichaelalonso** [comment]
Hola, GitHub es para problemas con la documentación. Visita la zona del foro de Feature Requests para sugerencias para la app:
https://community.infiniteflight.com/c/features/12

Gracias!
